/*
 * File: app/view/SelectEvent3.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SelectEvent3', {
    extend: 'Ext.Panel',

    config: {
        id: 'two',
        items: [
            {
                xtype: 'container',
                cls: [
                    'title'
                ],
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Join a basketball game',
                        labelWidth: '100%'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'map'
                ],
                items: [
                    {
                        xtype: 'map',
                        height: 250,
                        width: 317
                    },
                    {
                        xtype: 'button',
                        text: 'Start your own event'
                    }
                ]
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'container',
                        height: 41,
                        ui: '',
                        width: 316,
                        items: [
                            {
                                xtype: 'button',
                                centered: true,
                                width: 270,
                                text: '(location), (time), (#people)'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 34,
                        width: 319,
                        items: [
                            {
                                xtype: 'button',
                                centered: true,
                                height: 36,
                                width: 270,
                                text: '(location), (time), (#people)'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});