/*
 * File: app/view/ShareJoined9.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ShareJoined9', {
    extend: 'Ext.Panel',

    config: {
        cls: [
            'title'
        ],
        items: [
            {
                xtype: 'textfield',
                label: 'Join',
                labelWidth: '100%',
                readOnly: true
            },
            {
                xtype: 'formpanel',
                height: 105,
                width: 322,
                items: [
                    {
                        xtype: 'textfield',
                        height: 33,
                        padding: 0,
                        width: 292,
                        label: 'Congrats! You have joined an event',
                        labelWidth: '100%',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        centered: true,
                        height: 39,
                        padding: 0,
                        width: 208,
                        label: ' at (area) @ (time)',
                        labelWidth: '100%',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'button',
                margin: 20,
                text: 'Share on Facebook'
            },
            {
                xtype: 'button',
                margin: 20,
                text: 'Tweet'
            },
            {
                xtype: 'button',
                margin: 20,
                text: 'Get Directions'
            }
        ]
    }

});